//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class Acctrue_WMSEntities : DbContext
{
    public Acctrue_WMSEntities()
        : base("name=Acctrue_WMSEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<WMS_Bms_Back_Inv_Info> WMS_Bms_Back_Inv_Info { get; set; }
    public virtual DbSet<WMS_Bms_auto_GaiPan> WMS_Bms_auto_GaiPan { get; set; }
    public virtual DbSet<WMS_Bms_auto_GouHao> WMS_Bms_auto_GouHao { get; set; }
    public virtual DbSet<WMS_Bms_auto_PaoGou> WMS_Bms_auto_PaoGou { get; set; }
    public virtual DbSet<WMS_Bms_auto_ShouGou> WMS_Bms_auto_ShouGou { get; set; }
}
