//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class WMS_Bms_auto_GaiPan
{
    public int ID { get; set; }
    public string PCH { get; set; }
    public string GH { get; set; }
    public string SCX { get; set; }
    public string SX { get; set; }
    public string CURFLAG { get; set; }
    public string INSERTTIME { get; set; }
    public string UPDATETIME { get; set; }
    public string STATUS { get; set; }
    public string TM { get; set; }
    public string PH { get; set; }
    public string GG { get; set; }
    public string ZXBZ { get; set; }
    public string vfree1 { get; set; }
    public string vfree2 { get; set; }
    public string vfree3 { get; set; }
    public string wlh { get; set; }
    public string wlmc { get; set; }
    public string pcinfo { get; set; }
    public string gpyy { get; set; }
    public string gpflag { get; set; }
}

public partial class WMS_Bms_auto_GouHao
{
    public int ID { get; set; }
    public int GH { get; set; }
    public int NEXTGH { get; set; }
    public Nullable<int> PREGH { get; set; }
    public string PCH { get; set; }
    public string SCX { get; set; }
    public string CURFLAG { get; set; }
    public string UPDATETIME { get; set; }
    public string STATUS { get; set; }
    public string ISSHOUGOU { get; set; }
    public string ISPAOGOU { get; set; }
    public string ISGP { get; set; }
    public string GAIGOU { get; set; }
    public string INSERTTIME { get; set; }
    public string RFID { get; set; }
}

public partial class WMS_Bms_auto_PaoGou
{
    public int ID { get; set; }
    public int GH { get; set; }
    public string PCH { get; set; }
    public string SCX { get; set; }
    public string CURFLAG { get; set; }
    public string DR { get; set; }
    public string INSERTTIME { get; set; }
    public string UPDATETIME { get; set; }
    public string DRTIME { get; set; }
    public string SWITCHGH { get; set; }
    public string SWITCHTIME { get; set; }
    public string PCTIME { get; set; }
}

public partial class WMS_Bms_auto_ShouGou
{
    public int ID { get; set; }
    public string SCX { get; set; }
    public string PCH { get; set; }
    public string PCTIME { get; set; }
    public int GH { get; set; }
    public string CURFLAG { get; set; }
    public string INSERTTIME { get; set; }
    public string UPDATETIME { get; set; }
}

public partial class WMS_Bms_Back_Inv_Info
{
    public string Barcode { get; set; }
    public string WGDH { get; set; }
    public string CK { get; set; }
    public string HW { get; set; }
    public string PCH { get; set; }
    public string WLH { get; set; }
    public string WLMC { get; set; }
    public string SX { get; set; }
    public string ZLDJ { get; set; }
    public string PH { get; set; }
    public string GG { get; set; }
    public string BB { get; set; }
    public Nullable<int> GH { get; set; }
    public Nullable<decimal> ZL { get; set; }
    public string BZ { get; set; }
    public Nullable<System.DateTime> RQ { get; set; }
    public string RKType { get; set; }
    public string RKRY { get; set; }
    public Nullable<System.DateTime> WeightRQ { get; set; }
    public Nullable<System.DateTime> BackupRQ { get; set; }
    public string vfree0 { get; set; }
    public string vfree1 { get; set; }
    public string vfree2 { get; set; }
    public string vfree3 { get; set; }
    public string vfree4 { get; set; }
}
